version: '3'

services:
  wp:
    image: wordpress:latest 
    ports:
      - 8080:80 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "test"
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wp
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "test"
    ports:
      - 8181:80
    links:
      - db:db

  db:
    image: mysql:latest 
    ports:
      - 3306:3306 
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "test"

